import { Defaults } from "./interfaces"

export const Default: Defaults = {
  isLoading: false,
  assistants: [],
  assistant: {
    id: "",
    company_id: "",
    name: "",
    paused: false,
    purpose: null,
    description: null,
    avatar: null,
    llm: null,
    objective: null,
    identity: null,
    greetings: null,
    strategy: null,
    behavior: null,
    fallbacks: null,
    avoided_topics: null,
    step_by_step: null,
    goodbye: null,
    roles: null,
    behavior_text: null,
  },
  llms: [],
  followUpSteps: [],
  channel: {
    id: "",
    created_at: "",
    nome: "",
    tipoConexao: "",
    titular: "",
    assistant_id: "",
    ultimaAtualizacao: "",
    numeroTel: "",
    fotoPerfil: "",
    token: "",
    urlapi: "",
    apiUtilizada: "",
    status: "open",
    qrcode64: "",
    pairing_code: "",
    looping_qrcode: 0,
    instanceWpp: "",
    remoteJid: "",
  },
}
